stages:
  - build
  - deploy

include:
  - project: 'devops/ci-templates'
    file: '/php-nginx/gitlab-ci.yml'

variables:
  PROJECT_NAME: MyCent

################# Production #################

build-docker:
  extends: .build
  stage: build

  only:
    - master

  variables:
    ENV: prod
    TAG: latest

deploy-app:
  extends: .deploy
  stage: deploy
  only:
    - master

  needs:
    - build-docker

  variables:
    ENV: prod
    DESCRIPTION: "MyCent Production Stack"
    UPGRADE: server

################# /Production #################

################# Test #################

build-docker-test:
  extends: .build
  when: manual
  stage: build

  except:
    - master

  variables:
    ENV: test
    TAG: testing

deploy-test-app:
  extends: .deploy
  stage: deploy

  except:
    - master

  needs:
    - build-docker-test

  variables:
    ENV: test
    DESCRIPTION: "MyCent Test <$CI_COMMIT_REF_NAME>"
    UPGRADE: server

################# /Test #################
