version: '2'

#################################

networks:
  app_network:
    driver: bridge

volumes:
  mycent_production_mysql_data:
    driver: local
    external: true

  mycent_production_grafana_data:
    driver: local
    external: true

  mycent_production_redis_data:
    driver: local
    external: true

services:
  nginx:
    image: reg.cic.kz/centras-projects/mycent:nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - /share/common/mycent/shared/storage:/app/storage

    working_dir: /app

    networks:
      - app_network

    links:
      - php-lb
      - php-app

    depends_on:
      - php-lb
      - php-app

    labels:
      # io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: name=mycic
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

  ##############################################################################

  php-app:
    image: reg.cic.kz/centras-projects/mycent:fpm
    container_name: php-app
    hostname: php-app
    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

    environment: &env
      APP_DEBUG: "false"
      APP_KEY: "base64:SaYfcUjht1j8/4uJ810xTHG46S/yLjQ/AkYPJJWhsNQ="
      APP_ENV: "production"
      APP_URL: "https://mycent.kz/"

      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      DB_PORT: "3306"
      DB_DATABASE: "application"

      REDIS_HOST: "redis"
      CACHE_DRIVER: "file"
      QUEUE_CONNECTION: "database"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailtrap"
      MAIL_PORT: "25"
      MAIL_USERNAME: "mailtrap"
      MAIL_PASSWORD: "mailtrap"
      MAIL_ENCRYPTION: "null"
      MAIL_FROM_ADDRESS: "laravel@mycompany.com"
      MAIL_FROM_NAME: "Laravel"

      FRONTEND_DOMAIN: "doc30.kupipolis.kz"

      PUSHER_APP_ID: "874293"
      PUSHER_APP_KEY: "7be3a303223fdcdf62d5"
      PUSHER_APP_SECRET: "91d7feb674c6a3f29d46"
      PUSHER_APP_CLUSTER: "ap2"

      MIX_PUSHER_APP_KEY: "7be3a303223fdcdf62d5"
      MIX_PUSHER_APP_CLUSTER: "ap2"

      KIAS_URL: "http://192.168.1.26:8083/kiassvctest/kiassvc.asmx?wsdl"
      KIAS_LOGIN: "MyCIC"
      KIAS_PASSWORD: "mycickz321"

    volumes:
      - /app/storage:/share/common/mycent/shared/storage:ro

    networks:
      - app_network

    depends_on:
      - db

  ##############################################################################

  php-lb:
    image: rancher/lb-service-haproxy:v0.9.14
    hostname: php
    ports:
      - "9000:9000/tcp"

    depends_on:
      - php-app

    links:
      - php-app

    labels:
      io.rancher.scheduler.affinity:host_label: name=kupipolis
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

##############################################################################

  lb:
    image: rancher/lb-service-haproxy:v0.9.14
    hostname: lb
    ports:
      - "5555:5555/tcp"

    labels:
      io.rancher.scheduler.affinity:host_label: name=kupipolis
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

##############################################################################

  db:
    image: reg.cic.kz/centras/mysql:5.7
    container_name: Database
    hostname: db

    networks:
      - app_network

    volumes:
      - mycent_production_mysql_data:/var/lib/mysql

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=application

    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name

##############################################################################

  db-lb:
    image: rancher/lb-service-haproxy:v0.9.14
    ports:
      - "33306:3306"
    labels:
      io.rancher.scheduler.affinity:host_label: name=kupipolis
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'

##############################################################################

  pma:
    image: reg.cic.kz/centras/phpmyadmin:latest
    restart: always
    container_name: pma
    privileged: true

    ports:
      - "8082:80"

    links:
      - db

    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=
      - UPLOAD_LIMIT=1024M

    tty: true

    networks:
      - app_network

##############################################################################

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

    volumes:
      - mycent_production_redis_data:/data

    networks:
      - app_network

##############################################################################

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8089:3000"
    networks:
      - app_network
    volumes:
      - mycent_production_grafana_data:/var/lib/grafana
