version: '2'

#################################

networks:
  app_network:
    driver: bridge

volumes:
  mycent_production_postgres_data:
    driver: local
    # external: true

  mycent_production_grafana_data:
    driver: local
    # external: true

  mycent_production_redis_data:
    driver: local
    # external: true

services:
  server:
    image: reg.cic.kz/centras-projects/mycent:latest
    container_name: server
    hostname: server
    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

    ports:
      - "5556:80/tcp"

    environment: &env
      APP_DEBUG: "true"
      APP_KEY: "base64:SaYfcUjht1j8/4uJ810xTHG46S/yLjQ/AkYPJJWhsNQ="
      APP_ENV: "production"
      APP_URL: "http://192.168.30.31:4444/"

      DB_CONNECTION: "pgsql"
      DB_HOST: "pg"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "DVLkjNwEDZ9xMRPjG33b"
      DB_PORT: "5432"
      DB_DATABASE: "mycent_prod"

      REDIS_HOST: "redis"
      CACHE_DRIVER: "file"
      QUEUE_CONNECTION: "database"

      MAIL_MAILER: "smtp"
      MAIL_HOST: "mailtrap"
      MAIL_PORT: "25"
      MAIL_USERNAME: "mailtrap"
      MAIL_PASSWORD: "mailtrap"
      MAIL_ENCRYPTION: "null"
      MAIL_FROM_ADDRESS: "laravel@mycompany.com"
      MAIL_FROM_NAME: "Laravel"

      FRONTEND_DOMAIN: "mycent.kz"

      # KIAS_URL: "http://192.168.1.26:8083/kiassvctest/kiassvc.asmx?wsdl"
      # KIAS_LOGIN: "MyCIC"
      # KIAS_PASSWORD: "mycickz321"

      DEVELOPMENT_KEY: "123456789"

    volumes:
      - /home/student/mycent/shared/storage:/app/storage

    networks:
      - app_network

    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

    volumes: []
      # - mycent_production_redis_data:/data

    networks:
      - app_network

##############################################################################

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "7317:3000"
    networks:
      - app_network
    volumes: []
      # - mycent_production_grafana_data:/var/lib/grafana

    labels:
      io.rancher.scheduler.affinity:host_label: name=mycic
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
##############################################################################

  pg:
    image: postgres:12
    hostname: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: DVLkjNwEDZ9xMRPjG33b
    stdin_open: true
    volumes:
    - mycent_production_postgres_data:/var/lib/postgresql/data
    tty: true
    networks:
      - app_network
    labels:
      io.rancher.scheduler.affinity:host_label: type=internal

##############################################################################

  pgadmin:
    image: dpage/pgadmin4
    hostname: pg
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mycent.kz
      PGADMIN_DEFAULT_PASSWORD: DVLkjNwEDZ9xMRPjG33b
    ports:
      - "8090:80"
    stdin_open: true
    volumes:
    - mycent_production_postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    labels:
      io.rancher.scheduler.affinity:host_label: type=internal
