version: '2'

services:
  server:
    scale: 1
    start_on_create: true

###########################

  pg:
    scale: 1
    start_on_create: true

###########################

  pgadmin:
    scale: 1
    start_on_create: true

###########################

  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: frontend
        source_port: 7311
        target_port: 80
      - path: /api
        priority: 2
        protocol: http
        service: server
        source_port: 7311
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
